# Generated by Django 5.2.7 on 2025-12-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=' Название ')),
                ('description', models.TextField(blank=True, verbose_name=' Описание ')),
                ('category', models.CharField(choices=[('bike', 'Транспорт'), ('tool', 'Инструмент'), ('tech', 'Техника'), ('clothes', 'Одежда'), ('other', 'Другое')], default='other', max_length=20, verbose_name=' Категория ')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Цена в день, ₽ ')),
                ('is_available', models.BooleanField(default=True, verbose_name=' Доступна для аренды ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' Создана ')),
                ('location', models.CharField(blank=True, help_text='Город, район, адрес', max_length=255, verbose_name='Местоположение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name=' Владелец ')),
            ],
            options={
                'verbose_name': ' Вещь ',
                'verbose_name_plural': ' Вещи ',
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name=' Дата начала аренды ')),
                ('end_date', models.DateField(verbose_name=' Дата окончания аренды ')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('returned', 'Возвращена')], default='pending', max_length=20, verbose_name=' Статус ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' Создана ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='rentals.item', verbose_name=' Вещь ')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL, verbose_name=' Арендатор ')),
            ],
            options={
                'verbose_name': ' Заявка на аренду ',
                'verbose_name_plural': ' Заявки на аренду ',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - плохо'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - отлично')], verbose_name=' Оценка ')),
                ('text', models.TextField(blank=True, verbose_name=' Текст отзыва ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' Создан ')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL, verbose_name=' Автор отзыва ')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name=' Кому отзыв ')),
            ],
            options={
                'verbose_name': ' Отзыв о пользователе ',
                'verbose_name_plural': ' Отзывы о пользователях ',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
